#!/bin/bash

awk -F":" '{if ($1=="www-data") system("chown -R " $3":"$4 " /usr/share/zabbix/modules/NpServerSettings") }' /etc/passwd

if ! grep -qF 'www-data ALL=(ALL) NOPASSWD: /usr/share/zabbix/modules/NpServerSettings/bash/np_server_settings.sh' /etc/sudoers.d/visor; then
    echo 'www-data ALL=(ALL) NOPASSWD: /usr/share/zabbix/modules/NpServerSettings/bash/np_server_settings.sh' >> /etc/sudoers.d/visor
fi

chown root:root /usr/share/zabbix/modules/NpServerSettings/bash/np_server_settings.sh
chmod ugo+x /usr/share/zabbix/modules/NpServerSettings/bash/np_server_settings.sh
chmod u+s /usr/share/zabbix/modules/NpServerSettings/bash/np_server_settings.sh

exit 0
